---

- name: 'download Oracle Java 8 with wget'
  become: yes
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.rpm
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /tmp/jdk-8u111-linux-x64.rpm
  when: ansible_os_family == 'RedHat'
  register: download
  tags:
    - oracle_java8

- name: 'install Oracle Java 8'
  become: yes
  yum:
    name: /tmp/jdk-8u111-linux-x64.rpm
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  register: yuminstall
  tags:
    - oracle_java8

- name: 'download Oracle Java 8 with wget'
  become: yes
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /tmp/jdk-8u111-linux-x64.tar.gz
  when: ansible_os_family == 'Debian'
  register: download
  tags:
    - oracle_java8

- name: 'make sure /usr/lib/jvm exists'
  become: yes
  file: path=/usr/java state=directory owner=root mode=0755
  when: ansible_os_family == 'RedHat'
  tags:
    - oracle_java8

- name: 'make sure /usr/lib/jvm exists'
  become: yes
  file: path=/usr/lib/jvm state=directory owner=root mode=0755
  when: ansible_os_family == 'Debian'
  tags:
    - oracle_java8

- name: 'untar Oracle Java 8'
  unarchive: src=/tmp/jdk-8u111-linux-x64.tar.gz copy=no dest=/usr/lib/jvm
  when: ansible_os_family == 'Debian'
  tags:
    - oracle_java8

- name: 'Ensure presence of Java profile'
  become: yes
  file:
    path: /etc/profile.d/jre.sh
    state: touch
    mode: 0755
  tags:
    - oracle_java8

- name: 'fix JAVA_HOME'
  become: yes
  lineinfile:
    line: 'export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_111'
    dest: /etc/profile.d/jre.sh
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - oracle_java8

- name: 'fix JAVA_HOME'
  become: yes
  lineinfile:
    line: 'export JAVA_HOME=/usr/java/jdk1.8.0_111'
    dest: /etc/profile.d/jre.sh
    state: present
  when: ansible_os_family == 'RedHat'
  tags:
    - oracle_java8
