#!/usr/bin/env ansible-playbook
- name: RHEL7-CIS
  hosts: build
  become: yes

  roles:
  #  - ntp
    - RHEL7-CIS

  tasks:

    - name: install scap security guide
      yum: name=scap-security-guide state=present
