---
- name: Build Server 
  hosts: dev
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - bbaassssiiee.commoncentos
    - httpd
    
# Use Jenkins to build
    - jenkins

# nexus can be used as library repository
    - hullufred.nexus

# artifactory & sonar use mariadb
    - pcextreme.mariadb

# SonarQube can be used for reports
    - bbaassssiiee.sonar

# Artifactory can be used as build repository
    - bbaassssiiee.artifactory
  tasks:
    - include: tasks/settings.yml


- name: Test server 
  hosts: test
  user: root
  remote_user: vagrant
  sudo: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  roles:
    - bbaassssiiee.commoncentos
    - geerlingguy.java
    - hudecof.tomcat
#    - Ginsys.omnibus-gitlab

  tasks:
    - include: tasks/settings.yml

- name: Ubuntu Client
  hosts: ubuntu
  user: root
  remote_user: vagrant
  sudo: yes
  gather_facts: yes

  roles:
    - geerlingguy.java
    - ansible-maven
    - briancoca.oracle_java7
    - briancoca.selenium
    - ansible-eclipse
    - ThePixelDeveloper.google-chrome

  tasks:
    - include: tasks/client_setup.yml
