---

- src: dockpack.base_ant
- src: dockpack.base_boost
- src: dockpack.base_clang
- src: dockpack.base_cmake
- src: dockpack.base_common
- src: dockpack.base_docker
- src: dockpack.base_epel
- src: dockpack.base_gcc
- src: dockpack.base_git
- src: dockpack.base_goss
- src: dockpack.base_java8
- src: dockpack.base_maven
- src: dockpack.base_miniconda
- src: dockpack.base_nodejs
- src: dockpack.base_perl
- src: dockpack.base_postgres
- src: dockpack.base_python
- src: dockpack.base_utils
- src: dockpack.win_boost
- src: dockpack.win_buildtools
- src: dockpack.win_vscode

- src: https://github.com/bbaassssiiee/artifactory.git
  name: bbaassssiiee.artifactory
  version: master

- src: https://github.com/bbaassssiiee/sonar.git
  name: bbaassssiiee.sonar
  version: master

- src: https://github.com/bbaassssiiee/ansible-selenium-role.git

# Setup Windows machine as a Jenkins slave
- src: https://github.com/dockpack/ferhaty.jenkins-slave.git

- src: https://github.com/bbaassssiiee/windows-selenium-role.git

- src: https://github.com/bbaassssiiee/ansible-windows-java.git
  version: master
  name: ansible-windows-java

# For unix use a separate role
- src: https://github.com/bbaassssiiee/ansible-jenkins-slave.git

- src: https://github.com/jdauphant/ansible-role-nginx.git
  name: jdauphant.nginx
  version: v2.22
