---
- src: bbaassssiiee.commoncentos
  path: ./roles/

- src: Ginsys.omnibus-gitlab
  path: ./roles/

- src: hudecof.tomcat
  path: ./roles

- src: pcextreme.mariadb
  path: ./roles/

- src: bbaassssiiee.artifactory
  path: ./roles/

- src: bbaassssiiee.sonar
  path: ./roles/

- src: hullufred.nexus
  path: ./roles/

- src: geerlingguy.java
  path: ./roles/

- src: briancoca.oracle_java7
  path: ./roles

- src: https://github.com/bbaassssiiee/ansible-maven
  path: ./roles/

- src: briancoca.selenium
  path: ./roles

- src: https://github.com/AlbanAndrieu/ansible-eclipse.git
  path: ./roles

- src: ThePixelDeveloper.google-chrome
  path: ./roles
