    - name: 'add "dev" in /etc/hosts file'
      lineinfile: dest=/etc/hosts regexp='192.168.10.16'
              line='192.168.10.16   dev' 
              state=present

    - name: 'add "test" in /etc/hosts file'
      lineinfile: dest=/etc/hosts regexp='192.168.10.18'
              line='192.168.10.18   test' 
              state=present

    - name: 'install ubuntu-desktop (GUI)'
      apt: install_recommends=no name=ubuntu-desktop state=present

    - name: 'install ubuntu stuff'
      apt: name={{ item }} state=present
      with_items:
        - virtualbox-guest-dkms
        - flashplugin-installer
        - git

    - name: 'checkout OASIS'
      git: dest=/home/vagrant/OASIS
           repo=https://github.com/jguglielmi/OASIS-Maven.git
           force=yes

    - name: 'correct installer owner and permissions'
      file: path='/home/vagrant/OASIS/install.sh' state=file mode="u+rwx" owner=vagrant

    - name: 'install OASIS'
      shell: /home/vagrant/OASIS/install.sh chdir=OASIS/
             creates=/home/vagrant/.m2/repository/oasis/oasis-plugin/1.0/oasis-plugin-1.0.jar
      sudo: no

    - name: 'remove guest login'
      lineinfile: dest=/usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf regexp='^allow-guest'
              line='allow-guest=false' 
              state=present

    - name: 'reboot system if required'
      command: shutdown -r now 'Rebooting to complete system upgrade'
               removes=/var/run/reboot-required

