---

- include: python-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - python
    - redhat

- include: python-Debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - python
    - debian

- include: python-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - python
    - ubuntu

- name: 'update python setuptools'
  pip:
    name: setuptools
    state: latest
  tags:
    - skip_ansible_lint
    - python
    - setuptools

- name: 'make sure directory exists'
  become: yes
  file:
    dest: '/root/.pip'
    state: directory
    owner: root
    group: root
  tags:
    - python
    - pip

- name: 'deploy our own pip.conf config file'
  become: yes
  template:
    src: pip.j2
    dest: '/etc/pip.conf'
  tags:
    - python
    - pip

- name: 'upgrade pip from the pypi mirror'
  become: yes
  command: pip install pip --upgrade
  changed_when: no
  tags:
    - python
    - pip
    - test


- name: 'copy requirements.txt'
  copy:
    src: requirements.txt
    dest: '/tmp/requirements.txt'
  changed_when: no # temp file
  tags:
    - python
    - pip

- name: 'pip install dependencies'
  pip:
    requirements: '/tmp/requirements.txt'
    state: present
  tags:
    - python
    - pip
