---
- name: Install Git from yum repo
  become: yes
  yum: name=git state=present update_cache=yes
  when: ansible_os_family == 'RedHat'
  tags:
    - git

- name: Install Git from apt repo
  become: yes
  apt: name=git state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - git
