---

- name: 'make sure rpm_dependencies are installed'
  yum: name={{item}} state=installed
  when: ansible_os_family == "RedHat"
  register: installed
  retries: 3
  with_items: "{{ rpm_dependencies }}"
  tags:
    - jenkins
    - dependencies

- name: 'print red letters if import needed of CA root cert in Java trust store'
  command: "keytool -list -alias {{ inventory_hostname }} -keystore {{java_home}}/jre/lib/security/cacerts -storepass changeit -noprompt"
  ignore_errors: yes
  register: devkey
  tags:
    - jenkins
    - dependencies

- name: "import buildserverCA root cert in Java trust store"
  command: "keytool -importcert -trustcacerts -file /var/www/html/buildserverCA.cer -storepass changeit -noprompt -alias {{inventory_hostname}} -keystore {{java_home}}/jre/lib/security/cacerts"
  when: devkey.rc == 1
  tags:
    - jenkins
    - dependencies

- name: 'make sure jenkins_data directory exists'
  file: path={{jenkins_data}} owner=jenkins group=jenkins state=directory
  tags:
    - jenkins
    - dependencies

- name: 'make sure jenkins_tools directory exists'
  file: path={{jenkins_tools}} owner=jenkins group=jenkins mode=0755 state=directory
  tags:
    - jenkins
    - dependencies

- name: 'copy /etc/sysconfig/jenkins file to set the jenkins_data directory'
  template: src=jenkins.j2 dest=/etc/sysconfig/jenkins owner=root group=root mode=0644
  when: ansible_os_family == "RedHat"
  notify: 'restart jenkins'
  tags:
    - jenkins
    - dependencies
    - config
