---

- name: Add jenkins repository
  include: repo.yml

- name: Install dependencies (git, svn, etc)
  include: dependencies.yml

- name: Install jenkins
  include: jenkins.yml

- name: Run configuration
  include: config.yml
  tags: config

- name: Install demo game-of-life
  include: demo.yml
  tags:
    - demo

- name: Install jenkins command line tools
  include: cli.yml

# Stopped working in 2019
#- name: Install/update jenkins plugins
#  include: plugins.yml

#- name: enable passwords
#  include: security.yml

- name: Test jenkins
  include: test.yml
