---

python_rhel:
  - python
  - python-crypto
  - python-netaddr
  - python-nose
  - python-setuptools
  - pyOpenSSL

python_epel:
  - python-devel
  - python-cryptography
  - python-pip
  - python-pyasn1
  - libffi-devel
  - openssl-devel
  - python-httplib2
  - python-testtools
  - python-virtualenv

python_apts:
    - python
    - python-pip
    - libffi-dev
    - libssl-dev
    - python-dev
