---
- name: Set permissions on socket - owner
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^;?listen.owner'
    line: 'listen.owner = nginx'
  tags:
    - php

- name: Set permissions on socket - group
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^;?listen.group'
    line: 'listen.group = adm'
  tags:
    - php

- name: Set permissions on socket - mode
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^;?listen.mode'
    line: 'listen.mode = 0660'
  notify: restart php-fpm
  tags:
    - php

- name: Set user running php-fpm
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^user'
    line: 'user = nginx'
  tags:
    - php

- name: Set group running php-fpm
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^group'
    line: 'group = nginx'
  tags:
    - php

- name: Start php
  service:
    name: php-fpm
    state: started
    enabled: yes
  tags:
    - enabled
    - started

- name: Test PHP listening socket
  wait_for:
    host: localhost
    port: 9000
    timeout: 5
  ignore_errors: "{{ continue_on_error | default(True) }}"
  tags:
    - php
    - test
