---

- name: Copy test template
  template:
    src: pdo.php.j2
    dest: /usr/local/bin/pdo.php
    mode: 0700
  changed_when: no # reverting state after next action
  tags:
    - pdo_test
    - test
    - mysql_test

- name: Run mysql connect test
  command: /usr/local/bin/pdo.php
  changed_when: no
  no_log: yes
  ignore_errors: "{{ continue_on_error | default(True) }}"
  tags:
    - pdo_test
    - test
    - mysql_test

- name: Remove test template
  file:
    path: /usr/local/bin/pdo.php
    state: absent
  changed_when: no # reverting state now
  tags:
    - test
    - mysql_test
